# This workflow runs the crawler once a day.
name: Runs the crawler every day exactly at 11 AM Nepal Time (5:15 AM UTC) (Assuming offices open by 10 AM, so they upload news till 11 AM)

on:
 schedule:
   - cron: '15 5 * * *'
 # push:
   # branches: [ "main" ]

permissions:
  contents: write

jobs:
  crawl:
    name: Run crawlers for news
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install Python
        uses: actions/setup-python@v4.7.0
      
      - name: Install packages from PIP
        run: pip install -r requirements.txt

      - name: Prepare git config
        run: git config --global user.email "nightmaregaurav@users.noreply.github.com" && git config --global user.name "Gaurav Nyaupane"

      - name: Crawl nepalpolice.gov.np and extract news
        run: ./scripts/nepalpolice_gov_np.py

      - name: Update last crawled date info
        run: date > ./news/nepalpolice.gov.np/last_crawled_on.date

      - name: Commit the News from nepalpolice.gov.np
        run: git add --all && git commit -m "Crawled nepalpolice.gov.np on $(date)"

      - name: Push all changes
        run: git push
