# This workflow runs the crawler once a day.
name: Runs the crawler every day exactly at 11 AM Nepal Time (5:15 AM UTC) (Assuming offices open by 10 AM, so they upload news till 11 AM)

on:
 schedule:
   - cron: '15 5 * * *'
 # push:
   # branches: [ "main" ]

permissions:
  contents: write

jobs:
  crawl:
    name: Crawl Nepal police website (nepalpolice.gov.np) for news
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install Python
        uses: actions/setup-python@v4.7.0
      
      - name: Install packages from PIP
        run: pip install -r requirements.txt

      - name: Execute crawler script
        run: ./extract_nepali_crime_news.py

      - name: Prepare git config
        run: git config --global user.email "nightmaregaurav@users.noreply.github.com" && git config --global user.name "Gaurav Nyaupane"

      - name: Add dummy file to trigger an update
        run: date > last_crawled_on.date

      - name: Commit the change
        run: git add --all && git commit -m "Crawled on $(date)"

      - name: Push new file
        run: git push
